import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import fs from "fs";
import path from "path";

// Returns an autogenerated sidebar item only when the directory exists.
// This makes the sidebar resilient to schemas that lack certain type categories
// (e.g. no interfaces or inputs in a simple domain model).
function autoDir(dirName: string) {
  const abs = path.join(__dirname, "docs", dirName);
  return fs.existsSync(abs) ? [{ type: "autogenerated" as const, dirName }] : [];
}

export const insightsSidebar = [
  {
    type: "category" as const,
    label: "Overview",
    items: [
      { type: "link" as const, label: "Elements Breakdown", href: "/insights" },
      { type: "link" as const, label: "Composition Summary", href: "/insights/composition-summary" },
      { type: "link" as const, label: "Quality Summary", href: "/insights/quality-summary" },
    ],
  },
  {
    type: "category" as const,
    label: "Composition",
    items: [
      { type: "link" as const, label: "Largest Container Types by Fields", href: "/insights/largest-container-types-by-fields" },
      { type: "link" as const, label: "Scalar Distribution", href: "/insights/scalar-distribution" },
      { type: "link" as const, label: "Enum Usage", href: "/insights/enum-usage" },
    ],
  },
  {
    type: "category" as const,
    label: "Relationships",
    items: [
      { type: "link" as const, label: "References Count", href: "/insights/references-count" },
      { type: "link" as const, label: "Deepest Nested Paths", href: "/insights/deepest-nested-paths" },
      { type: "link" as const, label: "Cyclic References", href: "/insights/cyclic-references" },
    ],
  },
  {
    type: "category" as const,
    label: "Quality",
    items: [
      { type: "link" as const, label: "Documentation Coverage", href: "/insights/documentation-coverage" },
      { type: "link" as const, label: "Unused Elements", href: "/insights/unused-elements" },
      { type: "link" as const, label: "Missing Units", href: "/insights/missing-units" },
    ],
  },
];

export const ledgerSidebar = [
  { type: "link" as const, label: "Raw Tables", href: "/ledger" },
  { type: "link" as const, label: "Explore", href: "/ledger/explore" },
  { type: "link" as const, label: "Query", href: "/ledger/query" },
  { type: "link" as const, label: "Schema", href: "/ledger/schema" },
];

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "elements/schema",
    {
      type: "category" as const,
      label: "Types",
      items: [
        {
          type: "category" as const,
          label: "Field Containers",
          items: [
            { type: "category" as const, label: "Objects", items: autoDir("elements/types/objects") },
            { type: "category" as const, label: "Interfaces", items: autoDir("elements/types/interfaces") },
            { type: "category" as const, label: "Inputs", items: autoDir("elements/types/inputs") },
          ].filter((c) => c.items.length > 0),
        },
        { type: "category" as const, label: "Enums", items: autoDir("elements/types/enums") },
        { type: "category" as const, label: "Scalars", items: autoDir("elements/types/scalars") },
        { type: "category" as const, label: "Queries", items: autoDir("elements/operations/queries") },
      ].filter((c) => "items" in c && (c.items as unknown[]).length > 0),
    },
    {
      type: "category" as const,
      label: "Other",
      items: [
        { type: "category" as const, label: "Directives", items: autoDir("elements/types/directives") },
      ].filter((c) => c.items.length > 0),
    },
  ],
  insightsSidebar,
  ledgerSidebar,
};

export default sidebars;
